# Generated by Django 4.1.5 on 2023-10-27 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Employee_iD', models.CharField(max_length=12)),
                ('Name', models.CharField(max_length=10)),
                ('Email', models.EmailField(max_length=254)),
                ('Contact_Number', models.IntegerField()),
                ('date_of_joining', models.DateField()),
                ('Year_experience', models.IntegerField()),
            ],
        ),
    ]
